---
title: "lab-03"
subtitle: ESS330
author: 
  - name: Brandon Pizer
    email: bpizer@colostate.edu
format: html
---

```{r}
library(zoo)
library(flextable)
library(tidyverse)
library(usethis)
```

## Question 2

```{r}
url = 'https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv'
covid_data = read_csv(url)

```
```{r}

txt <- "2022-01-01"
class(txt)

date_example <- as.Date(txt)
class(date_example)

```
```{r}
my.date <- as.Date("2022-02-01")
my.state <- "Colorado"

```

```{r}
colorado <- covid_data |>
  filter(state == my.state) |>
  group_by(county) |>
  arrange(date) |>
  mutate(new_cases = cases - lag(cases),
         new_deaths = deaths - lag(deaths)) |>
  ungroup()


```

```{r}
filter(colorado, date == my.date) |>
  slice_max(cases, n = 5) |>
  select(Date = date, County = county, Cases = cases) |>
  flextable() |>
  set_caption("Most Total Cases in Colorado")

filter(colorado, date == my.date) |>
  slice_max(cases, n = 5) |>
  select(Date = date, County = county, Cases = new_cases) |>
  flextable() |>
  set_caption(caption = "Most New Cases in Colorado")


```
```{r}

pop_url <- 'https://www2.census



```

